# Generated by Django 4.2.5 on 2023-09-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome da Instituição')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
                ('instituicao_gestora', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_profissional', models.CharField(verbose_name='Registro Profissional')),
                ('codigo_cbo', models.CharField(verbose_name='Especialização CBO')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(verbose_name='Número de Telefone')),
                ('ddd', models.IntegerField()),
                ('pais', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(verbose_name='Email')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de Cadastro')),
                ('last_login', models.DateTimeField(verbose_name='Ultimo Login')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vinculo Ativo?')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.instituicao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField()),
                ('primeiro_nome', models.CharField(verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(verbose_name='Sobrenome')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.usuario')),
            ],
        ),
    ]
