# Generated by Django 4.2.5 on 2023-10-06 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=45, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=45, verbose_name='Nome da Rua')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome da Instituição')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
                ('instituicao_gestora', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999)], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('primeiro_nome', models.CharField(verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(verbose_name='Sobrenome')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_profissional', models.CharField(verbose_name='Registro Profissional')),
                ('codigo_cbo', models.CharField(verbose_name='Especialização CBO')),
                ('pessoa_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('senha', models.CharField(default=None, max_length=128, verbose_name='Senha')),
                ('data_cadastro', models.DateTimeField(auto_now=True, verbose_name='Data de Cadastro')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultimo Login')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vinculo Ativo?')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.instituicao')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(970000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Número de Telefone')),
                ('ddd', models.IntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(99)], verbose_name='DDD')),
                ('pais', models.IntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(99)], verbose_name='País de Origem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.usuario'),
        ),
        migrations.CreateModel(
            name='Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profissional')),
            ],
        ),
    ]
