# Generated by Django 4.2.5 on 2023-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_usuario_senha_alter_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Ultimo Login'),
        ),
    ]
